$kind: http-example
request:
  url: "{{baseUrl}}/inventory/:itemId"
  method: GET
  headers:
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  pathVariables:
    itemId: ""
response:
  statusCode: 404
  statusText: Not Found
  body:
    type: text
    content: ""
order: 2000
