$kind: http-example
request:
  url: "{{baseUrl}}/inventory/:itemId/adjust"
  method: POST
  headers:
    - key: Content-Type
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  pathVariables:
    itemId: ""
  body:
    type: json
    content: |-
      {
        "quantity": "<integer>",
        "reason": "cycle_count",
        "notes": "<string>"
      }
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
